### ISSUE TITLE
can bfdev give macro in lib?

### ISSUE THREAD

**Issue by ffashion** [openbfdev/bfdev#67]
env is changeable. if we give macro to user. user will get some compiler error if he copy bfdev to other same arch computer just env different. So we just give function to bfdev user ? . but this will cause performance low.

**Comment by John-sanpe** [comment]
I think we should design more than one set of alternative solutions, which can be composed of functions, and our preferred solution should maintain high performance as much as possible. Scheme selection can use macros to determine the environment, such as "__have_builtin".
